### ISSUE TITLE
Incompatible Composer Docker Image Version

### ISSUE THREAD

**Issue by mhottinger1** [apigee/docker-apigee-drupal-kickstart#21]
The Dockerfile uses a generic syntax to always choose the latest version of composer:2 … composer 2.4.2 has a breaking change that causes the Apigee Kickstart to throw a 500 error.

Workaround: pin the base composer image to 2.4.1.

**Comment by giteshk** [comment]
Thank you for reporting this @mhottinger1 ,

We have fixed the issue : https://github.com/apigee/docker-apigee-drupal-kickstart/commit/0b80869bda17a7e5bfc11f66beeab58cad6fa742

Please feel free to re-open if it still a problem.

**Comment by mhottinger1** [comment]
Thanks! I believe your fix has addressed the issue!
