### ISSUE TITLE
No docker image published, merge micovery/apigee-drupal8-dev-portal

### ISSUE THREAD

**Issue by cnovak** [apigee/docker-apigee-drupal-kickstart#6]
There is another docker project at https://github.com/micovery/apigee-drupal8-dev-portal. It would be good to consolidate to one project. What can we pull in from that project?

 https://github.com/micovery/apigee-drupal8-dev-portal/issues/3#issuecomment-592228887 points out that there isn't an image published from this repo. We should add one to make things easy for users.

**Comment by varuntit101** [comment]
Hi @cnovak, any update on this? Did we published this Image?

**Comment by cnovak** [comment]
No @varuntit101 I have not worked on this. @laughingbiscuit do you have any plans to publish the image?
